@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contentType = application/json

Post {{baseUrl}}/books
Content-Type: {{contentType}}

{
    "title": "O Senhor dos Anéis",
    "subtitle": "A sociedade do Anel",
    "author": "J.R.R Tolkien",
    "genre": "Fantasia",
    "cover": "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg"
}

###
GET {{baseUrl}}/books
Content-Type: {{contentType}}

###
GET {{baseUrl}}/books/66fbec122464a0b8cd2f25c2
Content-Type: {{contentType}}