@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contentType = application/json

//MÉTODO POST (MANDA ALGO PRO BANCO)
Post {{baseUrl}}/books
Content-Type: {{contentType}}

{
    "title": "O Senhor dos Anéis",
    "subtitle": "A sociedade do Anel",
    "author": "J.R.R Tolkien",
    "genre": "Fantasia",
    "cover": "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg"
}


//METODO GET ALL (CHAMA TODOS OS DADOS DO BANCO)
###
GET {{baseUrl}}/books
Content-Type: {{contentType}}

//METODO GET FOR ID (CHAMA UM ID ESPECIFICO)
###
GET {{baseUrl}}/books/670e6317ef3d3d7e0206f933
Content-Type: {{contentType}}

//METODO PUT (ATUALIZA AS INFORMAÇÕES DO BANCO)
###
PUT {{baseUrl}}/books/670e6317ef3d3d7e0206f933
Content-Type: {{contentType}}

{
    "title": "Biblia Sagrada",
    "subtitle": " ",
    "author" : "Muita Gente",
    "genre" : "Verdade",
    "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113624_84e92bc9-fe5b-4d2c-9c79-5d2153540499.jpg"
}
//METODO DELETE (DELETA UM LIVRO USANDO O ID
###
DELETE {{baseUrl}}/books/670e6317ef3d3d7e0206f933
Content-Type: {{contentType}}